# Generated by Django 2.1.1 on 2018-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeKer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(choices=[('TECH', 'Tecnologia'), ('INT', 'Interno'), ('INO', 'Inovação')], max_length=4)),
                ('status', models.CharField(choices=[('EST', 'Estagiário'), ('JUN', 'Júnior'), ('SEN', 'Sénior'), ('CEO', 'CEO'), ('COO', 'COO')], max_length=3)),
                ('mac_address', models.CharField(max_length=5)),
                ('presence', models.BooleanField(default=False)),
            ],
        ),
    ]
