# Generated by Django 2.1.1 on 2018-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeKers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=500)),
            ],
        ),
    ]
