# Generated by Django 2.1.1 on 2018-09-26 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jeKers', '0003_auto_20180925_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
